---
# Устанавливаем общие утилиты необходимые для работы
- name: Ensure the apt cache is up to date
  apt:
    update_cache: yes

- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

